(deftheme leuven-dark
  "Face colors with a dark background.
Basic, Font Lock, Isearch, Gnus, Message, Org mode, Diff, Ediff,
Flyspell, Semantic, and Ansi-Color faces are included -- and much
more...")

(custom-theme-set-variables
 'leuven-dark
 '(hl-sexp-background-color "#33323e")
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#ffffff" "#37ffff" "#e074e3" "#3732ff" "#ffff0b" "#37ff3c" "#ff400b" "#848088"]))

(custom-theme-set-faces
 'leuven-dark
 '(bold ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "#ffffff"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic :foreground "#e8e5eb"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#e1420b"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#cfccd2"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#b76130" :background "#25202a"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#3c312a"))))
 '(region ((((class color) (min-colors 89)) (:background "#752c0b"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:weight bold :background "#0601ff"))))
 '(isearch ((((class color) (min-colors 89)) (:underline "#ffffff" :foreground "#25202a" :background "#aa8b5e"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#06333d"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#0601ff"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#3a353f" :background "#252076"))))
 '(query-replace ((((class color) (min-colors 89)) (:inherit isearch))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:foreground "#322d37"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:foreground "#3a353f" :background "#25202a"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:foreground "#38ffff" :background "#06017f"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:foreground "#3a353f" :background "#25202a"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#3a353f" :background "#252076"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#e8d0b3") :foreground "#7e311e" :background "#cfa161"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#b5b1bb") :foreground "#322d38" :background "#696371"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#0601ff"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#0628ff"))))
 '(minibuffer-noticeable-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#0628ff"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ff7138"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(warning ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#ff01ff"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#ff9029"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#767283"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#767283"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#34c8d8"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#fd95fa"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#ff996f"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#ffff0b"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#837f87"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ff7fff"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#9fcb66"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#4ac964"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff"))))
 '(link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#1f879a"))))
 '(button ((((class color) (min-colors 89)) (:underline t :foreground "#ff925a"))))
 '(header-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#ffffff") :foreground "#ffffff" :background "#322d37"))))
 '(gnus-button ((((class color) (min-colors 89)) (:weight normal))))
 '(gnus-cite-attribution-face ((((class color) (min-colors 89)) (:foreground "#b3af59"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#b3af59" :background "#2d2832"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#9dffa1" :background "#2d2832"))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:foreground "#ff8890" :background "#2d2832"))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:foreground "#6bffff" :background "#2d2832"))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:foreground "#ffff6f" :background "#2d2832"))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:foreground "#4999ff" :background "#2d2832"))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:foreground "#b3af59" :background "#2d2832"))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:foreground "#9dffa1" :background "#2d2832"))))
 '(gnus-cite-9 ((((class color) (min-colors 89)) (:foreground "#ff8890" :background "#2d2832"))))
 '(gnus-cite-10 ((((class color) (min-colors 89)) (:foreground "#6bffff" :background "#2d2832"))))
 '(gnus-emphasis-bold ((((class color) (min-colors 89)) (:weight bold))))
 '(gnus-emphasis-highlight-words ((((class color) (min-colors 89)) (:foreground "#0601ff" :background "#ffffff"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#06af59"))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:foreground "#b3af59"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffa1"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:foreground "#9dffa1"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:foreground "#77737b"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#5b5660"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#5b5660"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#06af59"))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#b3af59"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffa1"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#9dffa1"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#77737b"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#6bffff"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#06ff6f"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#ffff6f"))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :foreground "#848088"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#837f87"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#9d99a1"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#ffffff"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#615c67"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#cf663d"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "#ffffff"))))
 '(gnus-picon ((((class color) (min-colors 89)) (:foreground "#0601ff" :background "#25202a"))))
 '(gnus-picon-xbm ((((class color) (min-colors 89)) (:foreground "#0601ff" :background "#25202a"))))
 '(gnus-server-closed ((((class color) (min-colors 89)) (:slant italic :foreground "#ffff0b" :background "#25202a"))))
 '(gnus-server-denied ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff" :background "#25202a"))))
 '(gnus-server-opened ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#25202a" :foreground "#bd9432"))))
 '(gnus-signature ((((class color) (min-colors 89)) (:slant italic :foreground "#787279"))))
 '(gnus-splash ((((class color) (min-colors 89)) (:foreground "#0673ff"))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#5b5660"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:weight bold :foreground "#eea682"))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#837f87"))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#06ccff"))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:weight bold :foreground "#eea682"))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:slant italic :foreground "#ffffff"))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:slant italic :foreground "#6b666f" :background "#413c46"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#06ccff"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:slant italic :foreground "#ffffff"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#77737b"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#77737b"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#06ccff"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#ff7332"))))
 '(gnus-x-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#25202a"))))
 '(message-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#615c67"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#ff925a"))))
 '(message-header-other ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#9d99a1"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "#ffffff"))))
 '(message-header-to ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#ff925a"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#b3af59" :background "#2d2832"))))
 '(message-separator ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#473d43"))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#cf663d"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#9d99a1"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#e074e3"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#442049"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#443f2a"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#7b777f"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:weight bold :foreground "#83ffff" :background "#252073"))))
 '(diff-file1-hunk-header ((((class color) (min-colors 89)) (:foreground "#78ff7c" :background "#382c33"))))
 '(diff-file2-hunk-header ((((class color) (min-colors 89)) (:foreground "#d781db" :background "#382c33"))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#38663d"))))
 '(diff-header ((((class color) (min-colors 89)) (:weight bold :foreground "#83ffff" :background "#252073"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#6bff6f" :background "#252f2a"))))
 '(diff-index ((((class color) (min-colors 89)) (:weight bold :foreground "#83ffff" :background "#252073"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#c966cc" :background "#53204e"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:background "#46302a"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#38ccd2" :background "#254046"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#6d0d73"))))
 '(diff-refine-change ((((class color) (min-colors 89)) (:background "#443f2a"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#06494f"))))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#25353e"))))
 '(smerge-mine ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#443f2a"))))
 '(smerge-other ((((class color) (min-colors 89)) (:background "#442049"))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#25353e"))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#253859"))))
 '(smerge-refined-change ((((class color) (min-colors 89)) (:background "#5a550b"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#253f49"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#442049"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#ff010b"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#312c36"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#312c36"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#06555f"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#ae01b2"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#312c36"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#312c36"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline (:style wave :color "#101487") :background "#292759" :inherit nil))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#0a5864") :background "#2f454c" :inherit nil))))
 '(semantic-decoration-on-unknown-includes ((((class color) (min-colors 89)) (:background "#252630"))))
 '(semantic-highlight-func-current-tag-face ((((class color) (min-colors 89)) (:background "#3a352a"))))
 '(semantic-tag-boundary-face ((((class color) (min-colors 89)) (:overline "#8c8890"))))
 '(Info-title-1-face ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(Info-title-2-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(Info-title-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#ffaae3" :background "#332038"))))
 '(Info-title-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#1a9cff"))))
 '(ace-jump-face-foreground ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#065aff"))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#3e392a"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:background "#064943"))))
 '(ahs-plugin-defalt-face ((((class color) (min-colors 89)) (:background "#25392a"))))
 '(anzu-match-1 ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#840135"))))
 '(anzu-match-2 ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "springgreen"))))
 '(anzu-match-3 ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#06ffff"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#830187"))))
 '(anzu-mode-line-no-match ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#067f87"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit query-replace))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:weight bold :foreground "#47cc0c" :background "#0742d2"))))
 '(auto-dim-other-buffers-face ((((class color) (min-colors 89)) (:background "#2c2731"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:background "#5b5660"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#065aff"))))
 '(bbdb-company ((((class color) (min-colors 89)) (:slant italic :foreground "#bd7d55"))))
 '(bbdb-field-name ((((class color) (min-colors 89)) (:weight bold :foreground "#bd7d55"))))
 '(bbdb-field-value ((((class color) (min-colors 89)) (:foreground "#bd7d55"))))
 '(bbdb-name ((((class color) (min-colors 89)) (:underline t :foreground "#0699d2"))))
 '(bmkp-light-autonamed ((((class color) (min-colors 89)) (:background "#322d37"))))
 '(bmkp-light-fringe-autonamed ((((class color) (min-colors 89)) (:foreground "#a9a5ad" :background "#302b35"))))
 '(bmkp-light-fringe-non-autonamed ((((class color) (min-colors 89)) (:foreground "#252059" :background "#fe010e"))))
 '(bmkp-light-non-autonamed ((((class color) (min-colors 89)) (:background "#60202a"))))
 '(bmkp-no-local ((((class color) (min-colors 89)) (:background "#063f3e"))))
 '(browse-kill-ring-separator-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(calendar-month-header ((((class color) (min-colors 89)) (:weight bold :foreground "#b4b5ca" :background "#252059"))))
 '(calendar-today ((((class color) (min-colors 89)) (:weight bold :foreground "#b4b5ca" :background "#252059"))))
 '(calendar-weekday-header ((((class color) (min-colors 89)) (:weight bold :foreground "#ec9d5a"))))
 '(calendar-weekend-header ((((class color) (min-colors 89)) (:weight bold :foreground "#b5b1b9"))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:foreground "#ff01ff" :background "#06ffff"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:foreground "#3b3640"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#d9ad66"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:foreground "#5b5660"))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#27222c"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#ec9d5a" :background "#25202a" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:foreground "#8c8890" :background "#3e322a"))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#9d7330" :slant italic))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#b5b1b9" :background "#25202a" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:foreground "#b96a1e" :background "#352d2e"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#b5b1b9" :background "#25202a" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:height 2.0 :foreground "#9c98a0" :weight bold :inherit variable-pitch))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:foreground "#b4b5ca" :background "#252059"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#eb9958"))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "#25202a"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:foreground "#35303a" :background "#25202a"))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:foreground "#a5a1a9" :background "#2d2832"))))
 '(change-log-date ((((class color) (min-colors 89)) (:foreground "#64df19"))))
 '(change-log-file ((((class color) (min-colors 89)) (:weight bold :foreground "#c27c45"))))
 '(change-log-list ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#8e1142"))))
 '(change-log-name ((((class color) (min-colors 89)) (:foreground "#ff7fff"))))
 '(circe-highlight-all-nicks-face ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#322d37"))))
 '(circe-highlight-nick-face ((((class color) (min-colors 89)) (:foreground "#ff6cff" :background "#322d37"))))
 '(circe-my-message-face ((((class color) (min-colors 89)) (:foreground "#78747c" :background "#322d37"))))
 '(circe-originator-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(circe-prompt-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(circe-server-face ((((class color) (min-colors 89)) (:foreground "#6b3524"))))
 '(comint-highlight-input ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :inherit nil))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :inherit nil))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#065aff"))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#372a2a"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:weight normal :foreground "#443f49" :inherit hl-line))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#372a2a"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#332525"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#2a3159" :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#ffad65"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#2a3159"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :foreground "#54ff59" :inherit company-tooltip))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#372a2a"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#deea0b"))))
 '(company-preview ((((class color) (min-colors 89)) (:weight normal :foreground "#443f49" :inherit hl-line))))
 '(company-preview-common ((((class color) (min-colors 89)) (:weight normal :foreground "#443f49" :inherit hl-line))))
 '(company-tooltip-scrollbar-track ((((class color) (min-colors 89)) (:background "#372a2a"))))
 '(company-tooltip-scrollbar-thumb ((((class color) (min-colors 89)) (:background "#332525"))))
 '(compare-windows ((((class color) (min-colors 89)) (:background "#0601ff"))))
 '(compilation-error ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight bold :foreground "#d8b76b"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:weight bold :foreground "#5fca5b"))))
 '(compilation-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:weight bold :foreground "#ff01ff"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:weight bold :foreground "#167d1b"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(css-property ((((class color) (min-colors 89)) (:foreground "#ff55ff"))))
 '(css-selector ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "gray20" :background "lightgrey"))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "#ffffff" :background "#3d3842"))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:box (:line-width 2 :style pressed-button) :foreground "#ffffff" :background "#312c36"))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:underline t :foreground "#78ff7c"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:underline t))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#ffff0b"))))
 '(custom-comment ((((class color) (min-colors 89)) (:background "#2b2630"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#ffff7c"))))
 '(custom-documentation ((((class color) (min-colors 89)) (nil))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "#ffff0b"))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "#06ffff"))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "#0601ff" :background "#06ffff"))))
 '(custom-link ((((class color) (min-colors 89)) (:underline t :foreground "#ffff0b"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#ffff0b"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "#063f3e" :background "#ffffff"))))
 '(custom-saved ((((class color) (min-colors 89)) (:underline t))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#25202a"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#ff74ff"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#ffff0b"))))
 '(custom-variable-button ((((class color) (min-colors 89)) (:weight bold :underline t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "#ffff0b"))))
 '(custom-visibility ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#ffff3c" :background "#46302a"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#37ffff" :background "#254046"))))
 '(diff-hl-dired-change ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#065cd0"))))
 '(diff-hl-dired-delete ((((class color) (min-colors 89)) (:weight bold :foreground "#2dc6ef"))))
 '(diff-hl-dired-ignored ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#44445e"))))
 '(diff-hl-dired-insert ((((class color) (min-colors 89)) (:weight bold :foreground "#4b464f"))))
 '(diff-hl-dired-unknown ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#c4c455"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#ff74ff" :background "#53204e"))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#c4c455"))))
 '(diary-face ((((class color) (min-colors 89)) (:foreground "#7c360d"))))
 '(dircolors-face-asm ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-backup ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-compress ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(dircolors-face-dir ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(dircolors-face-doc ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-dos ((((class color) (min-colors 89)) (:foreground "#e074e3"))))
 '(dircolors-face-emacs ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-exec ((((class color) (min-colors 89)) (:foreground "#e074e3"))))
 '(dircolors-face-html ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-img ((((class color) (min-colors 89)) (:foreground "#37ff3c"))))
 '(dircolors-face-lang ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-lang-interface ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-make ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-objet ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-package ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-paddb ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-ps ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-sound ((((class color) (min-colors 89)) (:foreground "#ff400b"))))
 '(dircolors-face-tar ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(dircolors-face-text ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dircolors-face-yacc ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(dired-directory ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(dired-header ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:strike-through t :foreground "#06ffff"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#e37233"))))
 '(diredfl-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#2526c0"))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:foreground "#64df19"))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(diredp-dir-name ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:background "#fd3fcb"))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "#e074e3" :background "#25202a"))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "#443f49"))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#848088"))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:background "#f7660b"))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#06bfc7"))))
 '(doom-modeline-panel ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#2526c0"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff" :background "#25392a"))))
 '(elfeed-search-filter-face ((((class color) (min-colors 89)) (:foreground "#46414b"))))
 '(eww-form-text ((((class color) (min-colors 89)) (:weight bold :foreground "#c3a798" :background "#5d3218"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:foreground "#848088"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "#06dae7" :style wave) :weight bold :background "#253c46"))))
 '(flycheck-error-list-line-number ((((class color) (min-colors 89)) (:foreground "#5fca5b"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#06dae7"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#ed75ef"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#1056cd"))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:color "#ed75ef" :style wave) :weight bold))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#1056cd" :style wave) :weight bold :background "#252066"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(fancy-narrow-blocked-face ((((class color) (min-colors 89)) (:foreground "#6b6765"))))
 '(flycheck-color-mode-line-error-face ((((class color) (min-colors 89)) (:background "#35a4b1"))))
 '(flycheck-color-mode-line-warning-face ((((class color) (min-colors 89)) (:background "#1938ff"))))
 '(flycheck-color-mode-line-info-face ((((class color) (min-colors 89)) (:background "#0601ff"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "#e8e5eb"))))
 '(font-latex-math-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:family "Sans Serif" :height 2.7 :weight bold :foreground "#9f6a1c"))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#ffaae3" :background "#332038"))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#1a9cff"))))
 '(font-latex-sedate-face ((((class color) (min-colors 89)) (:foreground "#06aaff"))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ff990b"))))
 '(font-latex-verbatim-face ((((class color) (min-colors 89)) (:foreground "#ffff7f" :background "#252046" :inherit nil))))
 '(git-commit-summary-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(git-commit-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#9a969e"))))
 '(git-timemachine-commit ((((class color) (min-colors 89)) (:background "#25353e"))))
 '(git-timemachine-minibuffer-author-face ((((class color) (min-colors 89)) (:background "#442049"))))
 '(git-timemachine-minibuffer-detail-face ((((class color) (min-colors 89)) (:weight bold :foreground "#83ffff" :background "#252073"))))
 '(google-translate-text-face ((((class color) (min-colors 89)) (:foreground "#8c8890" :background "#2e2933"))))
 '(google-translate-phonetic-face ((((class color) (min-colors 89)) (:inherit shadow))))
 '(google-translate-translation-face ((((class color) (min-colors 89)) (:weight normal :foreground "#d2861c" :background "#3f3336"))))
 '(google-translate-suggestion-label-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(google-translate-suggestion-face ((((class color) (min-colors 89)) (:slant italic :underline t))))
 '(google-translate-listen-button-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(helm-action ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-bookmarks-su-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(helm-buffer-modified ((((class color) (min-colors 89)) (:slant italic :foreground "#4ac964"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#ff7dff"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#0601a1"))))
 '(helm-dir-heading ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#063f3e"))))
 '(helm-dir-priv ((((class color) (min-colors 89)) (:foreground "#78ffff" :background "#312c36"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#ff32ff" :background "#25202a"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#0601ff" :background "#06ffff"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#e37233"))))
 '(helm-file-name ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(helm-gentoo-match-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:weight bold :foreground "#d8b76b"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:weight bold :foreground "#5fca5b"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:weight bold :background "#0601ff"))))
 '(helm-grep-running ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a"))))
 '(helm-isearch-match ((((class color) (min-colors 89)) (:background "#38013d"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:height 1.1 :underline nil :foreground "#25202a" :background "#66c96f"))))
 '(helm-ls-git-modified-not-staged-face ((((class color) (min-colors 89)) (:foreground "#4ac964"))))
 '(helm-match ((((class color) (min-colors 89)) (:weight bold :background "#0601ff"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#ff993d"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#cb8a33" :foreground "#25202a"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#3e3944"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#3d3842") :background "#433e48" :foreground "#ffffff"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 89)) (:background "#3833ff" :foreground "#e0dde3"))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 89)) (:background "#38330b"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 89)) (:weight bold :foreground nil :background "#0742d2"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(helm-w3m-bookmarks-face ((((class color) (min-colors 89)) (:underline t :foreground "#ff010b"))))
 '(highlight-changes ((((class color) (min-colors 89)) (:foreground nil))))
 '(highlight-changes-delete ((((class color) (min-colors 89)) (:strike-through nil :foreground nil))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#252080"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#2d2058"))))
 '(hl-tags-face ((((class color) (min-colors 89)) (:background "#3a352a"))))
 '(holiday-face ((((class color) (min-colors 89)) (:foreground "#8c8890" :background "#3e322a"))))
 '(html-helper-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(html-helper-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "#ffffff"))))
 '(html-helper-underline-face ((((class color) (min-colors 89)) (:underline t :foreground "#ffffff"))))
 '(html-tag-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(ilog-non-change-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#9fcb66"))))
 '(ilog-change-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#ff7dff"))))
 '(ilog-echo-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#ff9029"))))
 '(ilog-load-face ((((class color) (min-colors 89)) (:foreground "#4ac964"))))
 '(ilog-message-face ((((class color) (min-colors 89)) (:foreground "#837f87"))))
 '(indent-guide-face ((((class color) (min-colors 89)) (:foreground "#312c36"))))
 '(info-file ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.8 :weight bold :box (:line-width 1 :color "#ffff3d") :foreground "#9f6a1c" :background "#563c2a"))))
 '(info-header-node ((((class color) (min-colors 89)) (:underline t :foreground "#065aff"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:underline t :foreground "#e46f0b"))))
 '(info-index-match ((((class color) (min-colors 89)) (:weight bold :foreground nil :background "#0742d2"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(info-node ((((class color) (min-colors 89)) (:underline t :foreground "#ffff0b"))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#ff9bff" :background "#262031"))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#ff7fff"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(info-xref ((((class color) (min-colors 89)) (:underline t :foreground "#ff925a"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:underline t :foreground "#78ff7c"))))
 '(js2-error ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#06c8cf") :background "#063741"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#06ffff" :background "#252630"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#de8d83"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#6bcd3d"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#34c8d8"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#34c8d8"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:weight normal :foreground "#9fcb66"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#bd7d55"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:weight normal :foreground "#4ac964"))))
 '(js2-magic-paren ((((class color) (min-colors 89)) (:underline t))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#2a5ae5"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#375073"))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#065aff"))))
 '(leuven-dark-org-deadline-overdue ((((class color) (min-colors 89)) (:foreground "#12d9ae"))))
 '(leuven-dark-org-deadline-today ((((class color) (min-colors 89)) (:weight bold :foreground "#b4b5ca" :background "#252059"))))
 '(leuven-dark-org-deadline-tomorrow ((((class color) (min-colors 89)) (:foreground "#c357f8"))))
 '(leuven-dark-org-deadline-future ((((class color) (min-colors 89)) (:foreground "#c357f8"))))
 '(leuven-dark-gnus-unseen ((((class color) (min-colors 89)) (:weight bold :foreground "#088dfd"))))
 '(leuven-dark-gnus-date ((((class color) (min-colors 89)) (:foreground "#067f4a"))))
 '(leuven-dark-gnus-size ((((class color) (min-colors 89)) (:foreground "#7440a7"))))
 '(leuven-dark-todo-items-face ((((class color) (min-colors 89)) (:weight bold :foreground "#06cee0" :background "#06017f"))))
 '(light-symbol-face ((((class color) (min-colors 89)) (:background "#252080"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#6a656f" :background "#35303a"))))
 '(log-view-file ((((class color) (min-colors 89)) (:foreground "#ffff3d" :background "#382c33"))))
 '(log-view-message ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#171593"))))
 '(lsp-modeline-code-actions-preferred-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#2526c0"))))
 '(lsp-ui-doc-background ((((class color) (min-colors 89)) (:background "#2d2058"))))
 '(lsp-ui-sideline-code-action ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#2526c0"))))
 '(lui-button-face ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(lui-highlight-face ((((class color) (min-colors 89)) (:box '(:line-width 1 :color "#38ffff") :foreground "#38ffff" :background "#06017f"))))
 '(lui-time-stamp-face ((((class color) (min-colors 89)) (:foreground "#64df19"))))
 '(magit-blame-header ((((class color) (min-colors 89)) (:inherit magit-diff-file-header))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:overline "#5d5862" :foreground "#06ffff" :background "#3c3741"))))
 '(magit-blame-hash ((((class color) (min-colors 89)) (:overline "#5d5862" :foreground "#06ffff" :background "#3c3741"))))
 '(magit-blame-name ((((class color) (min-colors 89)) (:overline "#5d5862" :foreground "#fd95fa" :background "#3c3741"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:overline "#5d5862" :foreground "#ffff0b" :background "#3c3741"))))
 '(magit-blame-summary ((((class color) (min-colors 89)) (:overline "#5d5862" :weight bold :foreground "#938f97" :background "#3c3741"))))
 '(magit-branch ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#ff33d2") :foreground "#ffffff" :background "#5a015f"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:background "#442049"))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:background "#25353e"))))
 '(magit-diff-file-header ((((class color) (min-colors 89)) (:height 1.1 :weight bold :foreground "#c27c45"))))
 '(magit-diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#6bff6f" :background "#252f2a"))))
 '(magit-diff-none ((((class color) (min-colors 89)) (:foreground "#7b777f"))))
 '(magit-header ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#06bfc7"))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#382c33"))))
 '(magit-item-mark ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(magit-log-head-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#ffff0b" :style nil)))))
 '(magit-log-tag-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#ff33ff" :style nil)))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#2d2058"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.8 :weight bold :foreground "#9f6a1c" :inherit nil))))
 '(makefile-space-face ((((class color) (min-colors 89)) (:background "#069655"))))
 '(makefile-targets ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b"))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:inherit bold))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#ffaae3" :background "#332038"))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#1a9cff"))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#21da7a"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#ff883d"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "#ff9bff" :background "#262031"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:inherit italic))))
 '(markdown-language-keyword-face ((((class color) (min-colors 89)) (:inherit org-block-begin-line))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:weight normal :foreground "#ff925a"))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:inherit org-block-background))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :background "#0601ff"))))
 '(mc/cursor-bar-face ((((class color) (min-colors 89)) (:height 1.0 :foreground "#ec9b45" :background "#ec9b45"))))
 '(mc/cursor-face ((((class color) (min-colors 89)) (:inverse-video t))))
 '(mc/region-face ((((class color) (min-colors 89)) (:inherit region))))
 '(mm-uu-extract ((((class color) (min-colors 89)) (:foreground "#ffff7f" :background "#252046"))))
 '(moccur-current-line-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#252059"))))
 '(moccur-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#06016f"))))
 '(next-error ((((class color) (min-colors 89)) (:height 1.1 :underline nil :foreground "#25202a" :background "#66c96f"))))
 '(nobreak-space ((((class color) (min-colors 89)) (:background "#543532"))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground "#119cd0"))))
 '(nxml-attribute-value-delimiter-face ((((class color) (min-colors 89)) (:foreground "#ff74ff"))))
 '(nxml-attribute-value-face ((((class color) (min-colors 89)) (:foreground "#ff74ff"))))
 '(nxml-comment-content-face ((((class color) (min-colors 89)) (:slant italic :foreground "#06ffff"))))
 '(nxml-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(nxml-element-local-name ((((class color) (min-colors 89)) (:foreground "#56e46f"))))
 '(nxml-element-local-name-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(nxml-processing-instruction-target-face ((((class color) (min-colors 89)) (:foreground "#69cf0b"))))
 '(nxml-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(nxml-tag-slash-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(org-agenda-block-count ((((class color) (min-colors 89)) (:weight bold :foreground "#5f5a64"))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:weight bold :foreground "#cc8b3d" :background "#3e322a"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#d0853c" :background "#30272c"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#1636ff"))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#1e52b8" :background "#252c48"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:underline t :foreground "#ec9d5a"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#ec9d5a"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#b4b5ca" :background "#252059"))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#b5b1b9"))))
 '(org-agenda-diary ((((class color) (min-colors 89)) (:weight bold :foreground "#ff74ff" :background "#572723"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#1636ff"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#aeaab2"))))
 '(org-agenda-filter-category ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(org-agenda-filter-effort ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(org-agenda-filter-regexp ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(org-agenda-filter-tags ((((class color) (min-colors 89)) (:weight bold :foreground "#065aff"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#1d82a4"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#e37233"))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#514c56"))))
 '(org-beamer-tag ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#0a43ed") :foreground "#d6d3d9" :background "#252655"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#ffff7f" :background "#252046"))))
 '(org-block-background ((((class color) (min-colors 89)) (:background "#252046"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:underline "#5d595f" :foreground "#aeaab2" :background "#221e34"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:overline "#5d595f" :foreground "#aeaab2" :background "#221e34"))))
 '(org-checkbox ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :style pressed-button) :foreground "#efcab2" :background "#615c66"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#b98f7c"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#ff9bff" :background "#262031"))))
 '(org-column ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#1e52b8" :background "#252c48"))))
 '(org-column-title ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#1e52b8" :background "#252c48"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#ffba6b"))))
 '(org-default ((((class color) (min-colors 89)) (:foreground "#cfccd2" :background "#25202a"))))
 '(org-dim ((((class color) (min-colors 89)) (:foreground "#5a555f"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#bbb7bf"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#ff7138" :background "#38332a"))))
 '(org-document-title ((((class color) (min-colors 89)) (:height 1.8 :weight bold :foreground "#ffffff"))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#49444e") :foreground "#49444e" :background "#322d37"))))
 '(org-drawer ((((class color) (min-colors 89)) (:weight bold :foreground "#ff44ff" :background "#38203d"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:underline nil :foreground "#6b666f"))))
 '(org-example ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#38203d"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#ff7138"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#0680e1"))))
 '(org-habit-ready-face ((t :background "#7F9F7F")))
 '(org-habit-alert-face ((t :background "#E0CF9F" :foreground "#3F3F3F")))
 '(org-habit-clear-face ((t :background "#5C888B")))
 '(org-habit-overdue-face ((t :background "#9C6363")))
 '(org-habit-clear-future-face ((t :background "#4C7073")))
 '(org-habit-ready-future-face ((t :background "#5F7F5F")))
 '(org-habit-alert-future-face ((t :background "#D0BF8F" :foreground "#3F3F3F")))
 '(org-habit-overdue-future-face ((t :background "#8C5353")))
 '(org-headline-done ((((class color) (min-colors 89)) (:height 1.0 :weight normal :foreground "#57525c"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#403b45"))))
 '(org-inlinetask ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#37323c") :foreground "#8c8890" :background "#252050"))))
 '(org-latex-and-related ((((class color) (min-colors 89)) (:foreground "#cf996f" :background "#25202a"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#ffaae3" :background "#332038"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#1a9cff"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#21da7a"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#ff883d"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#d451d9"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#077ffa"))))
 '(org-link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(org-list-dt ((((class color) (min-colors 89)) (:weight bold :foreground "#cfa161"))))
 '(org-macro ((((class color) (min-colors 89)) (:weight bold :foreground "#1747fd"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:slant normal :foreground "#ff7138" :background "#38332a"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#cfa161") :foreground "#ffffff" :background "#065cd0"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#cfa161") :foreground "#25202a" :background "#06bfc7"))))
 '(org-number-of-items ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#8a458e"))))
 '(org-property-value ((((class color) (min-colors 89)) (:foreground "#ff5fff"))))
 '(org-quote ((((class color) (min-colors 89)) (:slant italic :foreground "#9a969e" :background "#252046"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#cfccd2"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ed9943"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:weight bold :foreground "#b4b5ca" :background "#252059"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#cc8b3d"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:weight bold :foreground "#ff44ff" :background "#38203d"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#ff9bff" :background "#38203d"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight normal :slant italic :foreground "#6a6065" :background "#25202a"))))
 '(org-target ((((class color) (min-colors 89)) (:foreground "#06925a"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#35303a"))))
 '(org-todo ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#2c5462") :foreground "#2c5462" :background "#253743"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#06aab2"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#ff993d" :background "#2c212a"))))
 '(org-verse ((((class color) (min-colors 89)) (:slant italic :foreground "#9a969e" :background "#342f39"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#54362a"))))
 '(outline-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#5d5862" :foreground "#c7c3cb" :background "#322d37"))))
 '(outline-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#efcab2" :foreground "#efcab2" :background "#3d2a2d"))))
 '(outline-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#ffaae3" :background "#332038"))))
 '(outline-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#1a9cff"))))
 '(outline-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#21da7a"))))
 '(outline-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#ff883d"))))
 '(outline-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#d451d9"))))
 '(outline-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#077ffa"))))
 '(pabbrev-debug-display-label-face ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#5edeb3"))))
 '(pabbrev-suggestions-face ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#06ffff"))))
 '(pabbrev-suggestions-label-face ((((class color) (min-colors 89)) (:weight bold :foreground "#25202a" :background "#64df19"))))
 '(paren-face-match ((((class color) (min-colors 89)) (:background "#7B4B98"))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:weight bold :underline "#06ffff" :foreground "#ffffff" :background "#065a64"))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:weight bold :underline "#06ffff" :foreground "#ffffff" :background "#065a64"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:weight bold :foreground "#34292a"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:foreground "#7e311e" :background "#cbc7ce" :inherit mode-line))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:foreground "#7e311e" :background "#c38f53" :inherit mode-line))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:foreground "#322d38" :background "#9b979f" :inherit mode-line-inactive))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:foreground "#322d38" :background "#5b5660" :inherit mode-line-inactive))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#938e84"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#907733"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#736e84"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#936797"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#738c94"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#a1894f"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#7e7a87"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#835787"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#7b8f97"))))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) (:weight bold :underline "#06ffff" :foreground "#ffffff" :background "#065a64"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:weight bold :underline "#06ffff" :foreground "#ffffff" :background "#065a64"))))
 '(recover-this-file ((((class color) (min-colors 89)) (:weight bold :background "#06c0c8"))))
 '(rng-error ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff" :background "#283a43"))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "#ffff0b" :background "#34292a"))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#06eb74"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#848088"))))
 '(shell-option-face ((((class color) (min-colors 89)) (:foreground "#e074e3"))))
 '(shell-output-2-face ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(shell-output-3-face ((((class color) (min-colors 89)) (:foreground "#64df19"))))
 '(shell-output-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(shm-current-face ((((class color) (min-colors 89)) (:background "#343551"))))
 '(shm-quarantine-face ((((class color) (min-colors 89)) (:background "lemonchiffon"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#7B4B98"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:weight bold :underline "#06ffff" :foreground "#ffffff" :background "#065a64"))))
 '(sml-modeline-end-face ((((class color) (min-colors 89)) (:background "#985213"))))
 '(sml-modeline-vis-face ((((class color) (min-colors 89)) (:background "#e9863f"))))
 '(term ((((class color) (min-colors 89)) (:foreground "#cfccd2" :background "#25202a"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "#ff74ff"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "#ffff7c"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "#ff747c"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:underline nil :foreground "#25202a" :background "#66c96f"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:underline t :foreground "#06ffff"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "#5fd5db"))))
 '(svn-status-directory-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffff0b" :background "#252053"))))
 '(svn-status-filename-face ((((class color) (min-colors 89)) (:weight bold :foreground "#c27c45"))))
 '(svn-status-locked-face ((((class color) (min-colors 89)) (:weight bold :foreground "#06ffff"))))
 '(svn-status-marked-face ((((class color) (min-colors 89)) (:foreground "#5affff" :background "#06555f"))))
 '(svn-status-marked-popup-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ff32ff"))))
 '(svn-status-switched-face ((((class color) (min-colors 89)) (:slant italic :foreground "#77737b"))))
 '(svn-status-symlink-face ((((class color) (min-colors 89)) (:foreground "#e37233"))))
 '(svn-status-update-available-face ((((class color) (min-colors 89)) (:foreground "#065aff"))))
 '(tex-verbatim ((((class color) (min-colors 89)) (:foreground "#ffff0b"))))
 '(tool-bar ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "#ffffff" :background "#45404a"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#252046"))))
 '(traverse-match-face ((((class color) (min-colors 89)) (:weight bold :foreground "#79d427"))))
 '(vc-annotate-face-3F3FFF ((((class color) (min-colors 89)) (:foreground "#c4c00b" :background "#ffffff"))))
 '(vc-annotate-face-3F6CFF ((((class color) (min-colors 89)) (:foreground "#c4c00b" :background "#ffffff"))))
 '(vc-annotate-face-3F99FF ((((class color) (min-colors 89)) (:foreground "#c4660b" :background "#ffffff"))))
 '(vc-annotate-face-3FC6FF ((((class color) (min-colors 89)) (:foreground "#c4660b" :background "#ffffff"))))
 '(vc-annotate-face-3FF3FF ((((class color) (min-colors 89)) (:foreground "#c40c0b" :background "#ffffff"))))
 '(vc-annotate-face-3FFF56 ((((class color) (min-colors 89)) (:foreground "#b801bc" :background "#ffffff"))))
 '(vc-annotate-face-3FFF83 ((((class color) (min-colors 89)) (:foreground "#c40159" :background "#ffffff"))))
 '(vc-annotate-face-3FFFB0 ((((class color) (min-colors 89)) (:foreground "#c40159" :background "#ffffff"))))
 '(vc-annotate-face-3FFFDD ((((class color) (min-colors 89)) (:foreground "#c40c0b" :background "#ffffff"))))
 '(vc-annotate-face-56FF3F ((((class color) (min-colors 89)) (:foreground "#b801bc" :background "#ffffff"))))
 '(vc-annotate-face-83FF3F ((((class color) (min-colors 89)) (:foreground "#5401c8" :background "#ffffff"))))
 '(vc-annotate-face-B0FF3F ((((class color) (min-colors 89)) (:foreground "#5401c8" :background "#ffffff"))))
 '(vc-annotate-face-DDFF3F ((((class color) (min-colors 89)) (:foreground "#060cc8" :background "#ffffff"))))
 '(vc-annotate-face-F6FFCC ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#252064"))))
 '(vc-annotate-face-FF3F3F ((((class color) (min-colors 89)) (:foreground "#06c0c8" :background "#ffffff"))))
 '(vc-annotate-face-FF6C3F ((((class color) (min-colors 89)) (:foreground "#06c0c8" :background "#ffffff"))))
 '(vc-annotate-face-FF993F ((((class color) (min-colors 89)) (:foreground "#0666c8" :background "#ffffff"))))
 '(vc-annotate-face-FFC63F ((((class color) (min-colors 89)) (:foreground "#0666c8" :background "#ffffff"))))
 '(vc-annotate-face-FFF33F ((((class color) (min-colors 89)) (:foreground "#060cc8" :background "#ffffff"))))
 '(vhl/default-face ((((class color) (min-colors 89)) (:underline nil :foreground "#25202a" :background "#66c96f"))))
 '(w3m-anchor ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(w3m-arrived-anchor ((((class color) (min-colors 89)) (:foreground "#69cf0b"))))
 '(w3m-bitmap-image-face ((((class color) (min-colors 89)) (:foreground "#f7f5f9" :background "#ff01ff"))))
 '(w3m-bold ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff"))))
 '(w3m-current-anchor ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "#ffff0b"))))
 '(w3m-form ((((class color) (min-colors 89)) (:underline t :foreground "#065ab8"))))
 '(w3m-form-button-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "#f7f5f9" :background "#312c36"))))
 '(w3m-form-button-mouse-face ((((class color) (min-colors 89)) (:underline t :foreground "#312c36" :background "#d781db"))))
 '(w3m-form-button-pressed-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "#f7f5f9" :background "#312c36"))))
 '(w3m-header-line-location-content-face ((((class color) (min-colors 89)) (:foreground "#848088" :background "#2c2731"))))
 '(w3m-header-line-location-title-face ((((class color) (min-colors 89)) (:foreground "#d6aa58" :background "#2c2731"))))
 '(w3m-history-current-url-face ((((class color) (min-colors 89)) (:foreground "#252458"))))
 '(w3m-image-face ((((class color) (min-colors 89)) (:weight bold :foreground "#501155"))))
 '(w3m-link-numbering ((((class color) (min-colors 89)) (:foreground "#50381e"))))
 '(w3m-strike-through-face ((((class color) (min-colors 89)) (:strike-through t))))
 '(w3m-underline-face ((((class color) (min-colors 89)) (:underline t))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#6b330b"))))
 '(web-mode-folded-face ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#8c8890") :foreground "#6a659d" :background "#110cbe"))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#119cd0"))))
 '(web-mode-html-tag-bracket-face ((((class color) (min-colors 89)) (:foreground "#56e46f"))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#56e46f"))))
 '(web-mode-part-face ((((class color) (min-colors 89)) (:background "#252046"))))
 '(web-mode-script-face ((((class color) (min-colors 89)) (:background "#332d37"))))
 '(which-func ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "#25202a"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 89)) (:weight bold :background "#30272c" :inherit which-key-command-description-face))))
 '(widget-button ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#ff925a"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#06ffff"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "#ff74ff"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#2b2630"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "#9a969e"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "#2b2630"))))
 '(woman-bold ((((class color) (min-colors 89)) (:weight bold :foreground "#13c2ca"))))
 '(woman-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "#bd41ea"))))
 '(woman-symbol ((((class color) (min-colors 89)) (:weight bold :foreground "#64df19"))))
 '(yas-field-debug-face ((((class color) (min-colors 89)) (:foreground "#25202a" :background "#5edeb3"))))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#807c84") :foreground "#ffffff" :background "#302331"))))
 '(ztreep-diff-model-add-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ff77ff"))))
 '(ztreep-diff-model-diff-face ((((class color) (min-colors 89)) (:weight bold :foreground "#ffbb2c"))))
 '(ztreep-diff-model-ignored-face ((((class color) (min-colors 89)) (:strike-through t :foreground "#66616b"))))
 '(ztreep-diff-model-normal-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#cfccd2" :background "#25202a")))))

(provide-theme 'leuven-dark)
